# coding: utf-8

"""
    Luno API

    The Luno API provides developers with a wealth of financial information provided through the Luno platform.  Through this secure system developers can:  <ul>    <li>Create accounts for trading in cryptocurrencies</li>    <li>Access current and historic cryptocurrency market data</li>    <li>Submit trade orders and view order status</li>    <li>Buy and sell Bitcoin and Ethereum</li>    <li>Send and receive Bitcoin and Ethereum</li>    <li>Generate Bitcoin and Ethereum wallet addresses</li>  </ul>   The Luno API brings the world of Bitcoin and Ethereum to your doorstep. 

    The version of the OpenAPI document: 1.2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from luno_openapi.api.beneficiaries_api import BeneficiariesApi


class TestBeneficiariesApi(unittest.TestCase):
    """BeneficiariesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BeneficiariesApi()

    def tearDown(self) -> None:
        pass

    def test_create_beneficiary(self) -> None:
        """Test case for create_beneficiary

        Create beneficiary
        """
        pass

    def test_delete_beneficiary(self) -> None:
        """Test case for delete_beneficiary

        Delete beneficiary
        """
        pass

    def test_list_beneficiaries(self) -> None:
        """Test case for list_beneficiaries

        List beneficiaries
        """
        pass


if __name__ == "__main__":
    unittest.main()
