# coding: utf-8

"""
Luno API

The Luno API provides developers with a wealth of financial information provided through the Luno platform.  Through this secure system developers can:  <ul>    <li>Create accounts for trading in cryptocurrencies</li>    <li>Access current and historic cryptocurrency market data</li>    <li>Submit trade orders and view order status</li>    <li>Buy and sell Bitcoin and Ethereum</li>    <li>Send and receive Bitcoin and Ethereum</li>    <li>Generate Bitcoin and Ethereum wallet addresses</li>  </ul>   The Luno API brings the world of Bitcoin and Ethereum to your doorstep.

The version of the OpenAPI document: 1.2.5
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from luno_openapi.api.orders_api import OrdersApi


class TestOrdersApi(unittest.IsolatedAsyncioTestCase):
    """OrdersApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = OrdersApi()

    def tearDown(self) -> None:
        pass

    def test_get_fee_info(self) -> None:
        """Test case for get_fee_info

        Get fee information
        """
        pass

    def test_get_order(self) -> None:
        """Test case for get_order

        Get order
        """
        pass

    def test_get_order_v2(self) -> None:
        """Test case for get_order_v2

        Get Order v2
        """
        pass

    def test_get_order_v3(self) -> None:
        """Test case for get_order_v3

        Get Order v3
        """
        pass

    def test_list_orders(self) -> None:
        """Test case for list_orders

        List orders
        """
        pass

    def test_list_orders_v2(self) -> None:
        """Test case for list_orders_v2

        List Orders v2
        """
        pass

    def test_list_user_trades(self) -> None:
        """Test case for list_user_trades

        List trades
        """
        pass

    def test_post_limit_order(self) -> None:
        """Test case for post_limit_order

        Post Limit Order
        """
        pass

    def test_post_market_order(self) -> None:
        """Test case for post_market_order

        Post Market Order
        """
        pass

    def test_stop_order(self) -> None:
        """Test case for stop_order

        Cancel Order
        """
        pass


if __name__ == "__main__":
    unittest.main()
