# coding: utf-8

"""
    Luno API

    The Luno API provides developers with a wealth of financial information provided through the Luno platform.  Through this secure system developers can:  <ul>    <li>Create accounts for trading in cryptocurrencies</li>    <li>Access current and historic cryptocurrency market data</li>    <li>Submit trade orders and view order status</li>    <li>Buy and sell Bitcoin and Ethereum</li>    <li>Send and receive Bitcoin and Ethereum</li>    <li>Generate Bitcoin and Ethereum wallet addresses</li>  </ul>   The Luno API brings the world of Bitcoin and Ethereum to your doorstep. 

    The version of the OpenAPI document: 1.2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from luno_openapi.models.order_v2 import OrderV2


class TestOrderV2(unittest.TestCase):
    """OrderV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderV2:
        """Test OrderV2
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `OrderV2`
        """
        model = OrderV2()
        if include_optional:
            return OrderV2(
                base = '',
                base_account_id = 56,
                client_order_id = '',
                completed_timestamp = '',
                counter = '',
                counter_account_id = 56,
                creation_timestamp = '',
                expiration_timestamp = '',
                fee_base = '',
                fee_counter = '',
                limit_price = '',
                limit_volume = '',
                order_id = '',
                pair = '',
                side = 'BUY',
                status = 'AWAITING',
                stop_direction = 'ABOVE',
                stop_price = '',
                time_in_force = '',
                type = 'LIMIT'
            )
        else:
            return OrderV2(
        )
        """

    def testOrderV2(self):
        """Test OrderV2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
