# coding: utf-8

"""
    Luno API

    The Luno API provides developers with a wealth of financial information provided through the Luno platform.  Through this secure system developers can:  <ul>    <li>Create accounts for trading in cryptocurrencies</li>    <li>Access current and historic cryptocurrency market data</li>    <li>Submit trade orders and view order status</li>    <li>Buy and sell Bitcoin and Ethereum</li>    <li>Send and receive Bitcoin and Ethereum</li>    <li>Generate Bitcoin and Ethereum wallet addresses</li>  </ul>   The Luno API brings the world of Bitcoin and Ethereum to your doorstep. 

    The version of the OpenAPI document: 1.2.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import find_packages, setup  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "luno-openapi"
VERSION = "1.2.5"
PYTHON_REQUIRES = ">=3.8"
REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "aiohttp >= 3.0.0",
    "aiohttp-retry >= 2.8.3",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Luno API",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Luno API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type="text/markdown",
    long_description="""\
    The Luno API provides developers with a wealth of financial information provided through the Luno platform.  Through this secure system developers can:  &lt;ul&gt;    &lt;li&gt;Create accounts for trading in cryptocurrencies&lt;/li&gt;    &lt;li&gt;Access current and historic cryptocurrency market data&lt;/li&gt;    &lt;li&gt;Submit trade orders and view order status&lt;/li&gt;    &lt;li&gt;Buy and sell Bitcoin and Ethereum&lt;/li&gt;    &lt;li&gt;Send and receive Bitcoin and Ethereum&lt;/li&gt;    &lt;li&gt;Generate Bitcoin and Ethereum wallet addresses&lt;/li&gt;  &lt;/ul&gt;   The Luno API brings the world of Bitcoin and Ethereum to your doorstep. 
    """,  # noqa: E501
    package_data={"luno_openapi": ["py.typed"]},
)
