# coding: utf-8

"""
    Luno API

    The Luno API provides developers with a wealth of financial information provided through the Luno platform.  Through this secure system developers can:  <ul>    <li>Create accounts for trading in cryptocurrencies</li>    <li>Access current and historic cryptocurrency market data</li>    <li>Submit trade orders and view order status</li>    <li>Buy and sell Bitcoin and Ethereum</li>    <li>Send and receive Bitcoin and Ethereum</li>    <li>Generate Bitcoin and Ethereum wallet addresses</li>  </ul>   The Luno API brings the world of Bitcoin and Ethereum to your doorstep. 

    The version of the OpenAPI document: 1.2.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing_extensions import Self


class Transfer(BaseModel):
    """
    Transfer
    """  # noqa: E501

    amount: Optional[StrictStr] = Field(
        default=None,
        description="Amount that has been credited or debited on the account. This is always a positive value regardless of the transfer direction.",
    )
    created_at: Optional[StrictInt] = Field(
        default=None,
        description="Unix timestamp the transfer was initiated, in milliseconds",
    )
    fee: Optional[StrictStr] = Field(
        default=None,
        description="Fee that has been charged by Luno with regards to this transfer. This is not included in the `amount`. For example, if you receive a transaction with the raw amount of 1 BTC and we charge a `fee` of 0.003 BTC on this transaction you will be credited the `amount` of 0.997 BTC.",
    )
    id: Optional[StrictStr] = Field(
        default=None, description="Transfer unique identifier"
    )
    inbound: Optional[StrictBool] = Field(
        default=None, description="True for credit transfers, false for debits."
    )
    transaction_id: Optional[StrictStr] = Field(
        default=None,
        description="When the transfer reflects an on-chain transaction this field will have the transaction ID.",
    )
    __properties: ClassVar[List[str]] = [
        "amount",
        "created_at",
        "fee",
        "id",
        "inbound",
        "transaction_id",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Transfer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Transfer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "amount": obj.get("amount"),
                "created_at": obj.get("created_at"),
                "fee": obj.get("fee"),
                "id": obj.get("id"),
                "inbound": obj.get("inbound"),
                "transaction_id": obj.get("transaction_id"),
            }
        )
        return _obj
